name: check-postgres

on:
  workflow_dispatch:
jobs:
  test-pg2:
    runs-on: ubuntu-latest
    steps:
      - name: Start Postgres
        if: runner.os == 'Windows'
        run: |
          cd "$PGBIN"
          ./pg_ctl start -o "-c max_connections=100"
          ./psql -U postgres -h localhost -c 'SELECT 1'
        shell: bash
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3