name: check-postgres

on:
  workflow_dispatch:
jobs:
  test-openssl:
    runs-on: windows-latest
  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: Setup tmate session
  #     uses: mxschmitt/action-tmate@v3
    steps:
      - uses: actions/checkout@v3
      # - run: mkdir -p target
      # - run: sudo mount -t tmpfs none ./target
      # - run: cat /proc/mounts | grep "$(pwd)" | sudo tee -a /etc/fstab
      - run: choco install openssl

      - uses: actions/checkout@v2
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
  
      # - run: cargo build --release