name: check-postgres

on:
  workflow_dispatch:
jobs:
  test-pg:
    runs-on: windows-latest
  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: Setup tmate session
  #     uses: mxschmitt/action-tmate@v3
    steps:
      - name: Initialse PG
        - run: pg_ctl start
        - run: psql -U postgres -c 'SELECT 1'
