name: check

on:
  workflow_dispatch:
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      # - name: Setup tmate session
      #   uses: mxschmitt/action-tmate@v3
      - name: Build Tests
        run: cargo build --tests --message-format=json > test_build_info.txt

      - name: Compress Tests
        run: | 
          grep -o '"executable":"[^"]*' test_build_info.txt | grep -o '[^"]*$' > binary_file_list.txt
          mkdir binary_files
          cat binary_file_list.txt | xargs -I '{}' mv '{}' ./binary_files/.
          tar -cf check.tar
        shell: bash
      
      - name: Archive Tests
        uses: actions/upload-artifact@v3
        with:
          name: test_binaries
          path: binary_files
  check2:
    runs-on: ubuntu-latest
    needs: check
    steps:
      - name: Download Test binaries
        uses: actions/download-artifact@v3

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3