name: check-postgres

on:
  workflow_dispatch:
jobs:
  test-front-end1:
    runs-on: buildjet-4vcpu-ubuntu-2004
    steps:
      - uses: actions/checkout@v3
      # - run: mkdir -p target
      # - run: sudo mount -t tmpfs none ./target
      # - run: cat /proc/mounts | grep "$(pwd)" | sudo tee -a /etc/fstab
      - run: cargo run
 
 jobs:
  test-front-end2:
    runs-on: buildjet-8vcpu-ubuntu-2004
    steps:
      - uses: actions/checkout@v3
      # - run: mkdir -p target
      # - run: sudo mount -t tmpfs none ./target
      # - run: cat /proc/mounts | grep "$(pwd)" | sudo tee -a /etc/fstab
      - run: cargo run
 
   jobs:
  test-front-end2:
    runs-on: buildjet-16vcpu-ubuntu-2004
    steps:
      - uses: actions/checkout@v3
      # - run: mkdir -p target
      # - run: sudo mount -t tmpfs none ./target
      # - run: cat /proc/mounts | grep "$(pwd)" | sudo tee -a /etc/fstab
      - run: cargo run

