name: Rust

on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened]
    paths: ["client/**"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - env:
         EVENT_CONTEXT: ${{ toJSON(github.event) }}
        run : |
          echo $EVENT_CONTEXT