name: Rust

on:
  workflow_dispatch:
   inputs:
      windows:
        description: 'Test on Windows'
        required: true 
        type: boolean 
      mac:
        description: 'Test on Mac'
        required: true 
        type: boolean
      linux:
        description: 'Test on Linux'
        required: true 
        type: boolean
  pull_request:
    paths: ["client/**"]

env:
  CARGO_TERM_COLOR: always

jobs:
  test-linux:
    if: ${{ inputs.linux || !github.event.inputs }}
    runs-on: ubuntu-latest
    steps:
      - env:
         EVENT_CONTEXT: ${{ toJSON(github.event) }}
        run : |
          echo $EVENT_CONTEXT
  test-windows:
    if: ${{ inputs.windows || !github.event.inputs }}
    runs-on: windows-latest
    steps:
      - env:
         EVENT_CONTEXT: ${{ toJSON(github.event) }}
        run : |
          echo $EVENT_CONTEXT
  test-mac:
    if: ${{ inputs.mac || !github.event.inputs  }}
    runs-on: macos-latest
    steps:
      - env:
         EVENT_CONTEXT: ${{ toJSON(github.event) }}
        run : |
          echo $EVENT_CONTEXT